//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "api_historic")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub key_id: i64,
    pub action: String,
    pub pkg_id: Option<i64>,
    pub created_at: DateTimeWithTimeZone,
    pub ip_address: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::api_keys::Entity",
        from = "Column::KeyId",
        to = "super::api_keys::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    ApiKeys,
    #[sea_orm(
        belongs_to = "super::packages::Entity",
        from = "Column::PkgId",
        to = "super::packages::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Packages,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::packages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Packages.def()
    }
}
