//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub mod prelude;

pub mod api_historic;
pub mod api_keys;
pub mod package_downloads;
pub mod packages;
pub mod templates;
pub mod users;
pub mod versions;
