//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.18

pub use super::api_historic::Entity as ApiHistoric;
pub use super::api_keys::Entity as ApiKeys;
pub use super::package_downloads::Entity as PackageDownloads;
pub use super::packages::Entity as Packages;
pub use super::templates::Entity as Templates;
pub use super::users::Entity as Users;
pub use super::versions::Entity as Versions;
